Musicify/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^music/', include('apps.music_app.urls', namespace="music")),
    url(r'^', include('apps.playlist_app.urls', namespace="playlists")),
    url(r'^users/', include('apps.user_app.urls', namespace="users")),
]

apps/music_app/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name="home"),
    url(r'^search$', search, name="search"),
    url(r'^add_artist_page$', add_artist_page, name="add_artist_page"),
    url(r'^add_artist$', add_artist, name="add_artist"),
    url(r'^songs/(?P<album_id>\d+)/$', songs, name="songs"),
    url(r'^add_song/(?P<album_id>\d+)/$', add_song, name="add_song"),
    url(r'^remove_song/(?P<song_id>\d+)/(?P<album_id>\d+)/$', remove_song, name="remove_song"),
]

apps/playlist_app/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name="home"),
    url(r'^add_to_playlist$', add_to_playlist, name="add_to_playlist"),
    url(r'^show_playlists$', show_playlists, name="show_playlists"),
    url(r'^create_playlist$', create_playlist, name="create_playlist"),
    url(r'^view_playlist/(?P<playlist_id>\d+)/$', view_playlist, name="view_playlist"),
    url(r'^edit_playlist/(?P<playlist_id>\d+)/$', edit_playlist, name="edit_playlist"),
    url(r'^update_playlist/(?P<playlist_id>\d+)/$', update_playlist, name="update_playlist"),
    url(r'^remove_playlist/(?P<playlist_id>\d+)/$', remove_playlist, name="remove_playlist"),
    url(r'^remove_song/(?P<song_id>\d+)/(?P<playlist_id>\d+)/$', remove_song, name="remove_song"),
]

apps/user_app/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name="home"),
    url(r'^register$', register, name="register"),
    url(r'^login$', login, name="login"),
    url(r'^profile$', profile, name="profile"),
    url(r'^edit_profile$', edit_profile, name="edit_profile"),
    url(r'^update_profile$', update_profile, name="update_profile"),
    url(r'^logout$', logout, name="logout"),
    url(r'^follow_users$', follow_users, name="follow_users"),
    url(r'^follow/(?P<followee_id>\d+)/$', follow, name="follow"),
    url(r'^unfollow/(?P<followee_id>\d+)/$', unfollow, name="unfollow"),
    url(r'^my_followers$', my_followers, name="my_followers"),
    url(r'^follower_profile/(?P<follower_id>\d+)$', follower_profile, name="follower_profile"),
]

apps/playlist_app/models.py
from __future__ import unicode_literals
from django.db import models
from ..user_app.models import User
from ..music_app.models import Song

# Create your models here.
class Playlist(models.Model):
    title = models.CharField(max_length=64)
    description = models.CharField(max_length=512)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Addition(models.Model):
    song = models.ForeignKey(Song, related_name="playlists")
    playlist = models.ForeignKey(Playlist)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Listener(models.Model):
    user = models.ForeignKey(User, related_name="favorite_playlists")
    playlist = models.ForeignKey(Playlist, related_name="listeners")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/playlist_app/views.py
from django.shortcuts import render, redirect, HttpResponse, reverse
import re
from django.contrib import messages
from .models import Playlist, Addition, Listener
from ..music_app.models import Song, Artist, Album

# Create your views here.
def index(request):
    context = {
        "songs": Song.objects.all()[:5].filter(),
        "playlists": Playlist.objects.all()[:5].filter(),
        "artists": Artist.objects.all()[:5].filter()
    }
    return render(request, 'playlist_app/index.html', context)

def add_to_playlist(request):
    if request.method == "POST":
        song_id = request.POST['song_id']
        playlist_id = request.POST['playlist_id']
    Addition.objects.create(song_id = song_id, playlist_id = playlist_id)
    return redirect('playlists:show_playlists')

def show_playlists(request):
    context = {
        "playlists": Playlist.objects.all()
    }
    return render(request, 'playlist_app/playlists.html', context)

def create_playlist(request):
    if request.method =='POST':
        playlist = Playlist.objects.create(title=request.POST['playlist_name'], description=request.POST['playlist_description'])
    return redirect('playlists:show_playlists')

def view_playlist(request, playlist_id):
    context = {
        "songs": Song.objects.filter(playlists__playlist_id=playlist_id),
        "playlist": Playlist.objects.get(id=playlist_id)
    }
    return render(request, 'playlist_app/view_playlist.html', context)

def edit_playlist(request, playlist_id):
    context = {
        "playlist": Playlist.objects.get(id=playlist_id)
    }
    return render(request, 'playlist_app/edit_playlist.html', context)

def update_playlist(request, playlist_id):
    if request.method=='POST':
        try:
            playlist = Playlist.objects.get(id=playlist_id)
            playlist.title = request.POST['playlist_title']
            playlist.description = request.POST['playlist_description']
            playlist.save()
            return redirect(reverse('playlists:view_playlist', kwargs={"playlist_id":playlist.id}))
        except:
            message.error(request, 'Inputs not valid, try again!')
            return redirect('playlists:edit_playlist')
    else:
        return redirect('playlists:edit_playlist')

def remove_playlist(request, playlist_id):
    Playlist.objects.get(id=playlist_id).delete()
    return redirect('playlists:show_playlists')

def remove_song(request, song_id, playlist_id):
    Addition.objects.get(song_id=song_id).delete()
    return redirect(reverse('playlists:view_playlist', kwargs={"playlist_id": playlist_id}))

apps/playlist_app/templates/playlist_app/edit_playlist.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <title>Edit Playlist</title>
</head>
<body>
  <h1>Edit "{{playlist.title}}"</h1>
  {% for m in messages %}
    <p>{{m}}</p>
  {% endfor %}
  <hr>
  <form action="{% url 'playlists:update_playlist' playlist_id=playlist.id %}" method="post">
    {% csrf_token %}
    Playlist Title: <input type="text" name="playlist_title" placeholder="{{playlist.title}}"><br><br><br>
    Playlist Description:<br>
    <textarea name="playlist_description" rows="8" cols="80" placeholder="{{playlist.description}}">
    </textarea><br><br><br>
    <input style="margin:10px; font-size:20pt;" type="submit" name="edit_playlist" value="Save Playlist">
  </form>
</body>
</html>

apps/playlist_app/templates/playlist_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Playlists</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
</head>
<body>
  <a href="{% url 'music:add_artist_page' %}">View Artists</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="{% url 'users:profile' %}">My Profile</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="{% url 'playlists:show_playlists' %}">My Playlists</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="{% url 'users:my_followers' %}">My Followers</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="{% url 'users:follow_users' %}">Follow Users</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  {% if request.session.email %}
    <a href="{% url 'users:logout' %}">Signout</a>
  {% else %}
    <a href="{% url 'users:home' %}">Login or Register</a>
  {% endif %}

  <h1>My Musicify</h1>
  <form action="{% url 'music:search' %}" method="post">
    {% csrf_token %}
    <input type="text" name="search_query">
    <input type="submit" name="search" value="Search">
  </form>
  <br>
  <hr>
  <br>
  <h3>Top 5 Songs</h3>
    <ol>
      {% for song in songs %}
      <li>{{song.title}}</li>
      {% endfor %}
    </ol>
  <br>
  <h3>Top 5 Artists</h3>
    <ol>
      {% for artist in artists %}
      <li>{{artist.name}}</li>
      {% endfor %}
    </ol>
  <br>
  <h3>Top 5 Playlists</h3>
  <ol>
    {% for playlist in playlists %}
    <li>{{playlist.title}}</li>
    {% endfor %}
  </ol>
</body>
</html>

apps/playlist_app/templates/playlist_app/playlists.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>My Playlists</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
</head>
<body>
  <a href="{% url 'music:add_artist_page' %}">View Artists</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="{% url 'playlists:home' %}">Home</a><br><br>
  <h1>Create a Playlist</h1>
  <hr><br>
  <form action="{% url 'playlists:create_playlist' %}" method="post">
    {% csrf_token %}
    Playlist Name: <input type="text" name="playlist_name"><br><br>
    Description: <br><textarea name="playlist_description" rows="8" cols="80"></textarea><br>
    <input style="font-size:20pt" type="submit" name="create_playlist" value="Create Playlist">
  </form>

  <h1>My Playlists</h1>
    <table style="border: 1px solid black;">
      <tr>
        <th style="border: 2px solid black; padding:10px 20px;">PLAYLISTS</th>
        <th style="border: 2px solid black; padding:10px 20px; width:400px;">DESCRIPTION</th>
      </tr>
      {% for playlist in playlists %}
        <tr>
          <td style="border: 1px solid black; padding:10px 20px;">{{playlist.title}}</td>
          <td style="border: 1px solid black; padding:10px 20px;">{{playlist.description}}</td>
          <td><a href="{% url 'playlists:view_playlist' playlist_id=playlist.id %}">View</a>&nbsp;&nbsp;&nbsp;&nbsp;
          <a href="{% url 'playlists:remove_playlist' playlist_id=playlist.id %}">Remove</a></td>
        </tr>
      {% endfor %}
    </table>

</body>
</html>

apps/playlist_app/templates/playlist_app/view_playlist.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Playlist Detail</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
</head>
<body>
  <a href="{% url 'music:add_artist_page' %}">View Artists</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="{% url 'playlists:home' %}">Home</a><br><br>
  <h1>{{playlist.title}}</h1>
  <h2>{{playlist.description}}</h2>
  <a href="{% url 'playlists:edit_playlist' playlist_id=playlist.id %}">Edit Playlist</a>
  <hr>
    <ol>
      {% for song in songs %}
      <li>{{song.title}}&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'playlists:remove_song' playlist_id=playlist.id song_id=song.id %}">Remove</a></li>
      {% endfor %}
    </ol>
</body>
</html>