Musicify/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^music/', include('apps.music_app.urls', namespace="music")),
    url(r'^', include('apps.playlist_app.urls', namespace="playlists")),
    url(r'^users/', include('apps.user_app.urls', namespace="users")),
]

apps/music_app/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name="home"),
    url(r'^search$', search, name="search"),
    url(r'^add_artist_page$', add_artist_page, name="add_artist_page"),
    url(r'^add_artist$', add_artist, name="add_artist"),
    url(r'^songs/(?P<album_id>\d+)/$', songs, name="songs"),
    url(r'^add_song/(?P<album_id>\d+)/$', add_song, name="add_song"),
    url(r'^remove_song/(?P<song_id>\d+)/(?P<album_id>\d+)/$', remove_song, name="remove_song"),
]

apps/playlist_app/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name="home"),
    url(r'^add_to_playlist$', add_to_playlist, name="add_to_playlist"),
    url(r'^show_playlists$', show_playlists, name="show_playlists"),
    url(r'^create_playlist$', create_playlist, name="create_playlist"),
    url(r'^view_playlist/(?P<playlist_id>\d+)/$', view_playlist, name="view_playlist"),
    url(r'^edit_playlist/(?P<playlist_id>\d+)/$', edit_playlist, name="edit_playlist"),
    url(r'^update_playlist/(?P<playlist_id>\d+)/$', update_playlist, name="update_playlist"),
    url(r'^remove_playlist/(?P<playlist_id>\d+)/$', remove_playlist, name="remove_playlist"),
    url(r'^remove_song/(?P<song_id>\d+)/(?P<playlist_id>\d+)/$', remove_song, name="remove_song"),
]

apps/user_app/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name="home"),
    url(r'^register$', register, name="register"),
    url(r'^login$', login, name="login"),
    url(r'^profile$', profile, name="profile"),
    url(r'^edit_profile$', edit_profile, name="edit_profile"),
    url(r'^update_profile$', update_profile, name="update_profile"),
    url(r'^logout$', logout, name="logout"),
    url(r'^follow_users$', follow_users, name="follow_users"),
    url(r'^follow/(?P<followee_id>\d+)/$', follow, name="follow"),
    url(r'^unfollow/(?P<followee_id>\d+)/$', unfollow, name="unfollow"),
    url(r'^my_followers$', my_followers, name="my_followers"),
    url(r'^follower_profile/(?P<follower_id>\d+)$', follower_profile, name="follower_profile"),
]

apps/music_app/models.py
from __future__ import unicode_literals
from django.db import models
from ..user_app.models import User

# Create your models here.
class Artist(models.Model):
    name = models.CharField(max_length=64, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Album(models.Model):
    title = models.CharField(max_length=64)
    artist = models.ForeignKey(Artist, related_name='albums')
    year = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Song(models.Model):
    album = models.ForeignKey(Album, related_name='songs')
    title = models.CharField(max_length=64)
    genre = models.CharField(max_length=64)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Fan(models.Model):
    user = models.ForeignKey(User, related_name='favorite_artists')
    artist = models.ForeignKey(Artist, related_name='fans')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/music_app/views.py
from django.shortcuts import render, redirect, HttpResponse, reverse
import re
from django.contrib import messages
from .models import Album, Artist, Song, Fan
from ..playlist_app.models import Playlist, Addition, Listener

# Create your views here.
def index(request):
    return render(request, 'music_app/index.html')

def add_artist_page(request):
    context = {
        "artists": Artist.objects.all().order_by('-created_at'),
    }
    return render(request, 'music_app/add_artist.html', context)

def add_artist(request):
    if request.method == "POST":
        try:
            artist = Artist.objects.create(name=request.POST['artist_name'])
            album = Album.objects.create(title=request.POST['album_name'], year=request.POST['album_year'], artist=artist)
        except:
            artist = Artist.objects.get(name=request.POST['artist_name'])
            album = Album.objects.create(title=request.POST['album_name'], year=request.POST['album_year'], artist=artist)
    return redirect('music:add_artist_page')

def songs(request, album_id):
    context = {
        "songs": Song.objects.filter(album_id = album_id).order_by('-created_at'),
        "album": Album.objects.get(id = album_id),
        "playlists": Playlist.objects.all(),
    }
    return render(request, 'music_app/songs.html', context)

def add_song(request, album_id):
    if request.method == "POST":
        song = Song.objects.create(title=request.POST['song_title'], genre=request.POST['song_genre'], album_id=album_id)
    return redirect(reverse('music:songs', kwargs={"album_id": album_id}))

def remove_song(request, song_id, album_id):
    song = Song.objects.get(id=song_id).delete()
    return redirect(reverse('music:songs', kwargs={"album_id": album_id}))

def search(request):
    if request.method=="POST":
        search_query = request.POST['search_query']
        try:
            songs = Song.objects.filter(title__contains = search_query)
            albums = Album.objects.filter(title__contains = search_query)
            artists = Artist.objects.filter(name__contains = search_query)
        except:
            messages.error(request, 'NO SEARCH RESULTS!! PLEASE TRY AGAIN')
            return redirect('playlists:home')
        context = {
            "songs": songs,
            "albums": albums,
            "artists": artists,
        }
    return render(request, 'music_app/search_results.html', context)

apps/music_app/templates/music_app/add_artist.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Artists and Albums</title>
</head>
<body>
  <a href="{% url 'playlists:home' %}">Home</a><br><br>
  <h1>Add an Artist and Album</h1>
  <hr><br>
  <form action="{% url 'music:add_artist' %}" method="post">
    {% csrf_token %}
    Artist Name: <input type="text" name="artist_name"><br><br>
    Album Name: <input type="text" name="album_name">&nbsp;&nbsp;&nbsp;&nbsp;
    Album Year: <input type="number" name="album_year"><br><br>
    <input style="font-size:20pt" type="submit" name="add_artist" value="Add">
  </form>
  <br><br><br>
  <h2>Artists and Albums</h2>
    <table style="border: 1px solid black;">
      <tr>
        <th style="border: 2px solid black;">ARTIST</th>
        <th style="border: 2px solid black; padding:10px">ALBUM</th>
      </tr>
      {% for artist in artists %}
      <tr>
        <td style="padding:10px;">{{artist.name}}</td>
        <td>
          <table style="border: 1px solid black; width:400px;">
            {% for album in artist.albums.all %}
            <tr>
              <td style="padding:15px;"><b>{{album.title}},</b> Released in {{album.year}}</td>
              <td><a href="{% url 'music:songs' album_id=album.id %}">View Songs</a></td>
            </tr>
            {% endfor %}
          </table>
        </td>
      </tr>
      {% endfor %}
    </table>

</body>
</html>

apps/music_app/templates/music_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Music</title>
</head>
<body>
  <h1>Hello Music!</h1>
</body>
</html>

apps/music_app/templates/music_app/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Search Results</title>
</head>
<body>
  <a href="{% url 'music:search' %}">Back to Search Results</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="{% url 'playlists:home' %}">Home</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="{% url 'users:profile' %}">My Profile</a><br><br>
  <h1>Search Results</h1>
  <br>
  {% for m in messages %}
    <p>{{m}}</p>
  {% endfor %}
  
  <h3>Songs</h3>
    {% for song in songs %}
    <ol>
      <li>{{song.title}} in <a href="{% url 'music:songs' album_id=song.album.id %}">{{song.album.title}}</a> by {{song.album.artist.name}}</li>
    </ol>
    {% endfor %}
<br><br><br>
<h3>Albums</h3>
  {% for album in albums %}
  <ol>
    <li><a href="{% url 'music:songs' album_id=album.id %}">{{album.title}}</a> by {{album.artist.name}}</li>
  </ol>
  {% endfor %}
<br><br><br>
<h3>Artists</h3>
  {% for artist in artists %}
  <ol>
    <li>{{artist.name}}</li>
  </ol>
  {% endfor %}
<br>
</body>
</html>

apps/music_app/templates/music_app/songs.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Songs</title>
</head>
<body>
  <h1>{{album.title}}, by {{album.artist.name}}</h1>
  <a href="{% url 'music:add_artist_page' %}">Back to Artists</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="{% url 'playlists:home' %}">Home</a><br><br>
  <h1>Add a Song</h1>
  <hr><br>
  <form action="{% url 'music:add_song' album_id=album.id %}" method="post">
    {% csrf_token %}
    Song Title: <input type="text" name="song_title">&nbsp;&nbsp;&nbsp;&nbsp;
    Genre:
      <select name="song_genre">
        <option value="">Pick a Genre</option>
        <option value="Rap/Hip-Hop">Rap/Hip-Hop</option>
        <option value="Rock">Rock</option>
        <option value="Country">Country</option>
        <option value="R&amp;B">R&amp;B</option>
        <option value="Jazz">Jazz</option>
        <option value="Reggae">Reggae</option>
        <option value="Latin">Latin</option>
        <option value="EDM">EDM</option>
        <option value="Funk">Funk</option>
        <option value="Pop">Pop</option>
        <option value="House">House</option>
      </select>
      <br><br>
    <input style="font-size:20pt" type="submit" name="add_song" value="Add Song">
  </form>
  <br><br><br>
  <h2>Songs in {{album.title}}</h2>
    <table style="border: 1px solid black;">
      <tr>
        <th style="border: 2px solid black;">SONGS</th>
        <th style="border: 2px solid black;">GENRE</th>
      </tr>
      {% for song in songs %}
        <tr>
          <td style="padding:10px 20px;">{{song.title}}</td>
          <td style="padding:0px 20px;">{{song.genre}}</td>
          <td style="padding:0px 20px;"><a href="{% url 'music:remove_song' song_id=song.id album_id=album.id %}">Remove Song</a></td>
          <td style="padding:0px 20px;">
            <form action="{% url 'playlists:add_to_playlist' %}" method="post">
              {% csrf_token %}
              <select class="playlist" name="playlist_id">
                <option disabled="disabled" selected="selected">Pick a Playlist</option>
                {% for playlist in playlists %}
                <option value="{{playlist.id}}">{{playlist.title}}</option>
                {% endfor %}
              </select>
              <input type="hidden" name="song_id" value="{{song.id}}">
              <input type="submit" value="Add to Playlist">
            </form>
          </td>
        </tr>
      {% endfor %}
    </table>
</body>
</html>