Musicify/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^music/', include('apps.music_app.urls', namespace="music")),
    url(r'^', include('apps.playlist_app.urls', namespace="playlists")),
    url(r'^users/', include('apps.user_app.urls', namespace="users")),
]

apps/music_app/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name="home"),
    url(r'^search$', search, name="search"),
    url(r'^add_artist_page$', add_artist_page, name="add_artist_page"),
    url(r'^add_artist$', add_artist, name="add_artist"),
    url(r'^songs/(?P<album_id>\d+)/$', songs, name="songs"),
    url(r'^add_song/(?P<album_id>\d+)/$', add_song, name="add_song"),
    url(r'^remove_song/(?P<song_id>\d+)/(?P<album_id>\d+)/$', remove_song, name="remove_song"),
]

apps/user_app/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name="home"),
    url(r'^register$', register, name="register"),
    url(r'^login$', login, name="login"),
    url(r'^profile$', profile, name="profile"),
    url(r'^edit_profile$', edit_profile, name="edit_profile"),
    url(r'^update_profile$', update_profile, name="update_profile"),
    url(r'^logout$', logout, name="logout"),
    url(r'^follow_users$', follow_users, name="follow_users"),
    url(r'^follow/(?P<followee_id>\d+)/$', follow, name="follow"),
    url(r'^unfollow/(?P<followee_id>\d+)/$', unfollow, name="unfollow"),
    url(r'^my_followers$', my_followers, name="my_followers"),
    url(r'^follower_profile/(?P<follower_id>\d+)$', follower_profile, name="follower_profile"),
]

apps/user_app/models.py
from __future__ import unicode_literals
from django.db import models


# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=64)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Friend(models.Model):
    follower = models.ForeignKey(User, related_name="followees")
    followee = models.ForeignKey(User, related_name="followers")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/user_app/views.py
from django.shortcuts import render, redirect, HttpResponse
import re
from django.contrib import messages
from .models import User, Friend


# Create your views here.
def index(request):
    return render(request, 'user_app/index.html')


def register(request):
    if request.method == "POST":
        server_firstname = request.POST['first_name']
        server_lastname = request.POST['last_name']
        server_email = request.POST['email']
        server_password = request.POST['password']
        try:
            user = User.objects.create(first_name=server_firstname, last_name=server_lastname, email=server_email, password=server_password)
            request.session['id'] = user.id
            request.session['first_name'] = user.first_name
            request.session['last_name'] = user.last_name
            request.session['email'] = user.email
            request.session['password'] = user.password
            return redirect('playlists:home')
        except:
            messages.error(request, 'ERROR: Email already exists!')
            return redirect('users:home')
    else:
        messages.error(request, 'ERROR: Login failed, try again!')
        return redirect('users:home')


def login(request):
    if request.method == "POST":
        server_email = request.POST['email']
        server_password = request.POST['password']
        try:
            user = User.objects.get(email=server_email)
            if user.password == server_password:
                request.session['id'] = user.id
                request.session['first_name'] = user.first_name
                request.session['last_name'] = user.last_name
                request.session['email'] = user.email
                return redirect('playlists:home')
            else:
                messages.error(request, 'ERROR: Incorrect Password!!')
                return redirect('users:home')
        except:
            messages.error(request, 'ERROR: Email not found!')
            return redirect('users:home')
    else:
        messages.error(request, 'ERROR: Login Invalid!')
        return redirect('users:home')


def profile(request):
    return render(request, 'user_app/profile.html')


def edit_profile(request):
    return render(request, 'user_app/edit_profile.html')


def update_profile(request):
    if request.method == "POST":
        server_firstname = request.POST['first_name']
        server_lastname = request.POST['last_name']
        server_password = request.POST['password']
        if server_password == request.POST['confirm_password']:
            try:
                user = User.objects.get(id = request.session['id'])
                user.first_name = server_firstname
                user.last_name = server_lastname
                user.password = server_password
                user.save()
                request.session['first_name'] = user.first_name
                request.session['last_name'] = user.last_name
                request.session['password'] = user.password
                return redirect('users:profile')
            except:
                messages.error(request, 'ERROR: Invalid inputs, try again!')
                return redirect('users:edit_profile')
        else:
            messages.error(request, 'ERROR: Passwords do not match, try again!')
            return redirect('users:edit_profile')
    else:
        messages.error(request, 'ERROR: Invalid inputs, try again!')
        return redirect('users:edit_profile')


def logout(request):
    request.session.clear()
    return redirect('users:home')


def follow_users(request):
    context = {
        "notfriends": User.objects.exclude(id=request.session['id']).exclude(followers__follower_id=request.session['id']),
        "friends": User.objects.filter(followers__follower_id=request.session['id'])
    }
    return render(request, 'user_app/follow_users.html', context)


def follow(request, followee_id):
    Friend.objects.create(follower_id=request.session['id'], followee_id=followee_id)
    return redirect('users:follow_users')


def unfollow(request, followee_id):
    Friend.objects.filter(followee_id=followee_id).delete()
    return redirect('users:follow_users')


def my_followers(request):
    context = {
        "my_followers": User.objects.filter(followers__follower_id=request.session['id'])
        }
    return render(request, 'user_app/my_followers.html', context)


def follower_profile(request, follower_id):
    context = {
        "friend": User.objects.get(id=follower_id)
    }
    return render(request, 'user_app/follower_profile.html', context)

apps/user_app/templates/user_app/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Edit My Profile</title>
</head>
<body>
  <a href="{% url 'users:profile' %}">Back to Profile</a>
  <br>
  <h1>Edit Your Profile</h1>
  <hr>
  {% for m in messages %}
    <p>{{m}}</p>
  {% endfor %}
  <br>
    <form action="{% url 'users:update_profile' %}" method="post">
      {% csrf_token %}
      First Name: <input type="text" name="first_name" placeholder="{{request.session.first_name}}"><br><br><br>
      Last Name: <input type="text" name="last_name" placeholder="{{request.session.last_name}}"><br><br><br>
      Password: <input type="password" name="password"><br><br><br>
      Confirm Password: <input type="password" name="confirm_password"><br><br><br>
      <input style="margin:10px; font-size:20pt;" type="submit" name="edit" value="Update Profile">
    </form>
</body>
</html>

apps/user_app/templates/user_app/follow_users.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Follow Users</title>
</head>
<body>
  <a href="{% url 'music:add_artist_page' %}">View Artists</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="{% url 'playlists:home' %}">Home</a><br><br>
  <h1>Follow Users</h1>
  {% for notfriend in notfriends %}
  <ul>
    <li>{{notfriend.first_name}} {{notfriend.last_name}}&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'users:follow' followee_id=notfriend.id %}">Follow</a></li>
  </ul>
  {% endfor %}
<hr>
  <h1>Unfollow Users</h1>
  {% for friend in friends %}
  <ul>
    <li>{{friend.first_name}} {{friend.last_name}}&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'users:unfollow' followee_id=friend.id %}">Unfollow</a></li>
  </ul>
  {% endfor %}

</body>
</html>

apps/user_app/templates/user_app/follower_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>My Profile</title>
</head>
<body>
  <a href="{% url 'users:my_followers' %}">Back to My Followers</a>&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="{% url 'playlists:home' %}">Home</a><br><br>
  <h1>{{friend.first_name}}'s Profile</h1>
  <hr><br
  <p>
    <b>First Name:</b> {{friend.first_name}} <br><br><br>
    <b>Last Name:</b> {{friend.last_name}} <br><br><br>
    <b>Email:</b> {{friend.email}} <br><br><br>
  </p>
</body>
</html>

apps/user_app/templates/user_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Users</title>
</head>
<body>
  <h1>Welcome Users!</h1>
  {% for m in messages %}
    <p>{{m}}</p>
  {% endfor %}
  <br><br>
  <h1>REGISTRATION</h1> <br>
    <form action="{% url 'users:register' %}", method="post">
      {% csrf_token %}
      First Name: <input type="text" name="first_name">
      Last Name: <input type="text" name="last_name">
      Email: <input type="email" name="email">
      Password: <input type="password" name="password">
      <input type="submit" name="register" value="Register">
    </form>
  <br><br>
  <h1>LOGIN</h1> <br>
  <form action="{% url 'users:login' %}", method="post">
    {% csrf_token %}
    Email Name: <input type="email" name="email">
    Password: <input type="password" name="password">
    <input type="submit" name="login" value="Login">
  </form>
</body>
</html>

apps/user_app/templates/user_app/my_followers.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>My Followers</title>
</head>
<body>
  <a href="{% url 'playlists:home' %}">Home</a><br><br>
  <h1>My Followers</h1>
  {% for follower in my_followers %}
  <ul>
    <li>{{follower.first_name}}&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'users:follower_profile' follower_id=follower.id %}">View Profile</a></li>
  </ul>
  {% endfor %}
</body>
</html>

apps/user_app/templates/user_app/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>My Profile</title>
</head>
<body>
  <a href="{% url 'users:edit_profile' %}">Edit Profile</a>&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="{% url 'playlists:home' %}">Home</a><br><br>
  <h1>{{request.session.first_name}}'s Profile</h1>
  <hr><br
  <p>
    <b>First Name:</b> {{request.session.first_name}} <br><br><br>
    <b>Last Name:</b> {{request.session.last_name}} <br><br><br>
    <b>Email:</b> {{request.session.email}} <br><br><br>
  </p>
</body>
</html>